sudo: required
dist: trusty

language: ruby

env:
  - DB=postgres
  - DB=mysql

gemfile:
  - gemfiles/spree_3_1.gemfile
  - gemfiles/spree_3_2.gemfile
  - gemfiles/spree_master.gemfile

before_script:
  - mkdir ../temp; cd ../temp
  - bundle exec rails _5.1.1_ plugin new spree_slider --mountable --dummy-path=spec/dummy --skip-test-unit
  - mv spree_slider/spec/dummy ../spec/
  - cd ../build; rm -rf ../temp

script:
  - bundle exec rspec spec

rvm:
  - 2.3.1
  - 2.2.7

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
